### ISSUE TITLE
Giving access to funds instead of sending to contract

### ISSUE THREAD

**Issue by seichris** [LinkdropProtocol/Product-Feedback#5]
We got feedback that the user could send by giving the contract access to his funds, instead of sending them to the contract.

**Comment by Dobrokhvalov** [comment]
@seichris We have this in our roadmap and @amiromayer is working now to add approve pattern to our contracts (https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/139). 
We will add it in Linkdrop PRO release

**Comment by seichris** [comment]
great! closing because duplicate
